language: node_js
node_js:
- '11.15.0'
beforescript:
- npm install -g gulp
- npm install
script:
- gulp package-app
deploy:
  api_key:
    secure: nnX2WMJxaq8KqXAQCzOit0i58yjWG/Ij0pXKMlYOSFZIhSmhmMe78XqfJnvvNXR5TEmLUV1X8FLq2OeLmYZqlA0uuxaL5EGkIgGmsWYcrV+srxNjNDrb/eFN2x/++pRo+ZQbliu2sC//Z70xZ4S9q1+LxacuJHuA1QBmoP7P+4nUb0h4JVfjp/TlgVUytmR588ggoubR/lFL8gNROfNOi0FunAsPdaOtC8dnCzwr8gAbXwSBMUwI/Gv4oX5wI/RhSG3WsvgnukchZHrwdwf8mZPBp+wFCoPXxKK07OMAXkNLtAF26IF53Ini2Hr6l2/jvG1f4V4jjdsHYLJRiN+anl8DI9KHDsSjZI9BIcNz6qXk/zVWTfH+KUY0Pqt8KntJjMqvN2b+cFoGEek+JWbeEE+V93irSUNP+k4sajmCdW3SODS5I0Nycs0OSHwR+ONhQFrjFoAynmEzeUwp42gOgq0pqJ4rgn8WnQ+fgKg8QeudC7lvp/a2ugJLfpqjUfYEx3SE7Pvwxdb3WvNxNLwud94a4sviWCMCUF0Hf+3qnwfmLsk5SBFNxfp6FXolE03Tur7KMQnij4aMQKJIzXmwXGnPG3G0V7C3mfjCjyIwF2+iN8oW+LZsacgagUePJZW2RogDZPQZqUldL/PrdL8SzTHhyotIkzUkOi2e58iwB3M=
  provider: heroku
  app: dp-creative-app
